// Copyright 2020 Adam Chalkley
//
// https://github.com/atc0005/check-cert
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/atc0005/check-certs/internal/logging"
)

// Updated via Makefile builds. Setting placeholder value here so that
// something resembling a version string will be provided for non-Makefile
// builds.
var version string = "x.y.z"

const myAppName string = "check_cert"
const myAppURL string = "https://github.com/atc0005/check-cert"

const (
	sansEntriesHelp  string = "Subject Alternate Names (SANs) expected for the certifciate used by the remote service. This value is provided as a comma-separated list."
	logLevelFlagHelp string = "Sets log level to one of disabled, panic, fatal, error, warn, info, debug or trace."
	serverHelp       string = "The fully-qualified domain name of the remote system whose cert(s) will be monitored."
	portHelp         string = "TCP port of the remote certificate-enabled service. This is usually 443 (HTTPS) or 636 (LDAPS)."
	ageWarningHelp   string = "The number of days remaining before certificate expiration when Nagios will return a WARNING state"
	ageCriticalHelp  string = "The number of days remaining before certificate expiration when Nagios will return a CRITICAL state"
	brandingFlagHelp string = "Toggles emission of branding details with plugin status details. This output is disabled by default."
)

// Default flag settings if not overridden by user input
const (
	defaultLogLevel    string = "info"
	defaultServer      string = "localhost"
	defaultPort        int    = 993
	defaultAgeWarning  int    = 30
	defaultAgeCritical int    = 15
	defaultBranding    bool   = false
)

// multiValueFlag is a custom type that satisfies the flag.Value interface in
// order to accept multiple values for some of our flags.
type multiValueFlag []string

// String returns a comma separated string consisting of all slice elements.
func (i *multiValueFlag) String() string {

	// From the `flag` package docs:
	// "The flag package may call the String method with a zero-valued
	// receiver, such as a nil pointer."
	if i == nil {
		return ""
	}

	return strings.Join(*i, ", ")
}

// Set is called once by the flag package, in command line order, for each
// flag present.
func (i *multiValueFlag) Set(value string) error {

	// split comma-separated string into multiple folders, toss whitespace
	items := strings.Split(value, ",")
	for index, item := range items {
		items[index] = strings.TrimSpace(item)
	}

	// add them to the collection
	*i = append(*i, items...)
	return nil
}

// Config represents the application configuration as specified via
// command-line flags.
type Config struct {

	// SANsEntries is the list of Subject Alternate Names (SANs) to verify are
	// present on the examined certificate. This value is provided a
	// comma-separated list.
	SANsEntries multiValueFlag

	// Server is the fully-qualified domain name of the system running a
	// certificate-enabled service.
	Server string

	// Port is the TCP port used by the certifcate-enabled service.
	Port int

	// LoggingLevel is the supported logging level for this application.
	LoggingLevel string

	// AgeWarning is the number of days remaining before certificate
	// expiration when this application will flag the NotAfter certificate
	// field as a WARNING state.
	AgeWarning int

	// AgeWarning is the number of days remaining before certificate
	// expiration when this application will flag the NotAfter certificate
	// field as a CRITICAL state.
	AgeCritical int

	// EmitBranding controls whether "generated by" text is included at the
	// bottom of application output. This output is included in the Nagios
	// dashboard and notifications. This output may not mix well with branding
	// output from other tools such as atc0005/send2teams which also insert
	// their own branding output.
	EmitBranding bool
}

// Usage is a custom override for the default Help text provided by the flag
// package. Here we prepend some additional metadata to the existing output.
var Usage = func() {
	fmt.Fprintf(flag.CommandLine.Output(), "%s %s\n%s\n\n", myAppName, version, myAppURL)
	fmt.Fprintf(flag.CommandLine.Output(), "Usage of %s:\n", os.Args[0])
	flag.PrintDefaults()
}

// Branding emits application name and version information. This function is
// intended to be called with the defer keyword early in the execution of
// main() in order to run last after the service check output is emitted.
func Branding() {
	fmt.Printf("\nNotification generated by %s (%s)\n", myAppName, version)
}

func (c *Config) handleFlagsConfig() {

	flag.Var(&c.SANsEntries, "sans-entries", sansEntriesHelp)
	flag.IntVar(&c.AgeWarning, "age-warning", defaultAgeWarning, ageWarningHelp)
	flag.IntVar(&c.AgeCritical, "age-critical", defaultAgeCritical, ageCriticalHelp)
	flag.StringVar(&c.Server, "server", defaultServer, serverHelp)
	flag.IntVar(&c.Port, "port", defaultPort, portHelp)
	flag.StringVar(&c.LoggingLevel, "log-level", defaultLogLevel, logLevelFlagHelp)
	flag.BoolVar(&c.EmitBranding, "branding", defaultBranding, brandingFlagHelp)

	// Allow our function to override the default Help output
	flag.Usage = Usage

	// parse flag definitions from the argument list
	flag.Parse()

}

// Validate verifies all Config struct fields have been provided acceptable
// values.
func (c Config) Validate() error {

	if c.SANsEntries == nil {
		return fmt.Errorf("one or more SANs entries not provided")
	}

	if c.Port < 0 {
		return fmt.Errorf("invalid TCP port number %d", c.Port)
	}

	if c.AgeWarning < 0 {
		return fmt.Errorf("invalid value for warning age: %d", c.AgeWarning)
	}

	if c.AgeCritical < 0 {
		return fmt.Errorf("invalid value for critical age: %d", c.AgeCritical)
	}

	if c.AgeCritical > c.AgeWarning {
		return fmt.Errorf("critical threshold set higher than warning threshold; review Nagios service check and command definition")
	}

	if c.Server == "" {
		return fmt.Errorf("server FQDN not provided")
	}

	requestedLoggingLevel := strings.ToLower(c.LoggingLevel)
	if _, ok := logging.LoggingLevels[requestedLoggingLevel]; !ok {
		return fmt.Errorf("invalid logging level %q", c.LoggingLevel)
	}

	// Optimist
	return nil

}
